### ISSUE TITLE
bio dependencies

### ISSUE THREAD

**Issue by mjy** [nexml/bio-nexml#9]
@pjotrp besides the namespacing, does this library require code outside of /lib? My superficial assessment is that it doesn't.

It's been a while since I've dived into /bio, so this is an ignorant question, but could you briefly highlight reasons for not extracting this library to a stand-alone gem without the overhead of the rest of bio?

**Comment by pjotrp** [comment]
Nexml is a phylogenetic format that can be used outside bio. I don't think there are any real dependencies on bio. Feel free to remove.

**Comment by yeban** [comment]
Sorry, there is. bio-nexml's [trees](https://github.com/nexml/bio-nexml/blob/master/lib/bio/db/nexml/trees.rb) are derived from bio's.

Any problem with dependencies is with the xml parser (libxml-ruby).

**Comment by pjotrp** [comment]
So, if you want to move out, create another tree object. Should not be too hard. Bio is pure Ruby, so hardly a real issue.

**Comment by pjotrp** [comment]
I think this issue can be closed. It is not really a bug.

**Comment by mjy** [comment]
I agree, but since when are issues always bugs?
